In [1]:
import numpy as np

In [2]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

How many negative numbers are there?

In [3]:
len(a[a % 2 != 0])

4

How many positive numbers are there?

In [4]:
len(a[~a % 2 != 0])

8

How many even positive numbers are there?

In [5]:
len(a[(a % 2 == 0) & (a > 0)])

3

If you were to add 3 to each data point, how many positive numbers would there be?

In [6]:
len(a[ (a + 3 > 0)])

10

If you squared each number, what would the new mean and standard deviation be?

In [7]:
b_values = a**2
print( "Standard deviations = ", b_values.std(), "\n Mean = ", b_values.mean())

Standard deviations =  144.0243035046516 
 Mean =  74.0


A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.

In [8]:
c_values = a - a.mean()
c_values

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

Calculate the z-score for each data point. Recall that the z-score is given by:
          x
Z =     ______
        μ * σ

In [9]:
d_values = a / (a.mean() * a.std())
d_values

array([ 0.16537965,  0.41344912,  0.49613894,  0.95093297, -0.08268982,
       -0.04134491,  0.        ,  0.        ,  0.        , -0.24806947,
        0.12403473, -0.28941438])

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [10]:
## Setup 1
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [11]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

In [12]:
sum_of_a = a.sum()
sum_of_a

55

In [13]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

In [14]:
min_of_a = a.min()
min_of_a

1

In [15]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

In [16]:
max_of_a = a.max()
max_of_a

10

In [17]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list

In [18]:
mean_of_a = a.mean()
mean_of_a

5.5

In [19]:
# Exercise 5 - Make a variable named product_of_a to hold the product of:
# multiplying all the numbers in the above list together

In [20]:
product_of_a = a.prod()
product_of_a

3628800

In [21]:
# Exercise 6 - Make a variable named squares_of_a. 
#It should hold each number in a squared like [1, 4, 9, 16, 25...]

In [22]:
squares_of_a = a ** 2
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [23]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers

In [24]:
odds_of_a = a[a % 2 != 0]
odds_of_a

array([1, 3, 5, 7, 9])

In [25]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.

In [26]:
evens_of_a = a[a % 2 == 0]
evens_of_a

array([ 2,  4,  6,  8, 10])

### What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...

Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.

In [27]:
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [28]:
# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable.

**Hint, you'll first need to make sure that the "b" variable is a numpy array**

In [29]:
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

In [30]:
b_np = np.array(b)

In [31]:
sum_of_b = np.sum(b_np, axis=0)
sum_of_b

array([ 9, 11, 13])

In [32]:
# Exercise 2 - refactor the following to use numpy. 

min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])

In [33]:
min_of_b = b_np.min()
min_of_b

3

In [34]:
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.

max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

In [35]:
max_of_b = b_np.max()
max_of_b

8

In [36]:
# Exercise 4 - refactor the following using numpy to find the mean of b

mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

In [37]:
mean_of_b = b_np.mean()
mean_of_b

5.5

In [38]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

product_of_b = 1

for row in b:
    for number in row:
        product_of_b *= number

In [39]:
product_of_b = b_np.prod()
product_of_b

20160

In [40]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 

squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)

In [41]:
squares_of_b = b_np ** 2
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [42]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)

In [43]:
odds_in_b = b_np[b_np % 2 != 0]
odds_in_b

array([3, 5, 7])

In [44]:
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)

In [45]:
evens_in_b = b_np[b_np % 2 == 0]
evens_in_b

array([4, 6, 8])

In [46]:
# Exercise 9 - print out the shape of the array b.

In [47]:
np.shape(b_np)

(2, 3)

In [48]:
# Exercise 10 - transpose the array b.

In [49]:
np.transpose(b_np)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [50]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

In [51]:
n_np_flat = np.reshape(b_np,(1,6))
n_np_flat

array([[3, 4, 5, 6, 7, 8]])

In [52]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)

In [53]:
n_np_tall = np.reshape(b_np,(6,1))
n_np_tall

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [54]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [55]:
c_np = np.array(c)

HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.

In [56]:
# Exercise 1 - Find the min, max, sum, and product of c.
print(c_np.min())
print(c_np.max())
print(c_np.sum())
print(c_np.prod())

1
9
45
362880


In [57]:
# Exercise 2 - Determine the standard deviation of c.

In [58]:
c_np.std()

2.581988897471611

In [59]:
# Exercise 3 - Determine the variance of c.

In [60]:
c_np.var()

6.666666666666667

In [61]:
# Exercise 4 - Print out the shape of the array c

In [62]:
print(np.shape(c_np))

(3, 3)


In [63]:
# Exercise 5 - Transpose c and print out transposed result.

In [64]:
print(np.transpose(c_np))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [65]:
# Exercise 6 - Get the dot product of the array c with c. 

In [66]:
new_thing = c_np.prod() * c_np.prod()
new_thing

131681894400

In [67]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

In [68]:
complex_answer = sum(sum(c_np * np.transpose(c_np)))
complex_answer

261

In [69]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. 
# Answer should be 131681894400.

In [70]:
prod_answer = np.prod(c_np * np.transpose(c_np))
prod_answer

131681894400

In [71]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [82]:
d_np = np.array(d)

In [72]:
# Exercise 1 - Find the sine of all the numbers in d

In [84]:
np.sin(d_np)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [73]:
# Exercise 2 - Find the cosine of all the numbers in d

In [85]:
np.cos(d_np)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [74]:
# Exercise 3 - Find the tangent of all the numbers in d

In [86]:
np.tan(d_np)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [75]:
# Exercise 4 - Find all the negative numbers in d

In [87]:
d_np[d_np < 0]

array([-90, -30, -45, -45])

In [76]:
# Exercise 5 - Find all the positive numbers in d

In [88]:
d_np[d_np > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [77]:
# Exercise 6 - Return an array of only the unique numbers in d.

In [89]:
np.unique(d_np)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [78]:
# Exercise 7 - Determine how many unique numbers there are in d.

In [91]:
len(np.unique(d_np))

11

In [79]:
# Exercise 8 - Print out the shape of d.

In [92]:
np.shape(d_np)

(3, 6)

In [80]:
# Exercise 9 - Transpose and then print out the shape of d.

In [94]:
np.shape(np.transpose(d_np))

(6, 3)

In [81]:
# Exercise 10 - Reshape d into an array of 9 x 2

In [95]:
np.reshape(d_np, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])